### ISSUE TITLE
Gradle example

### ISSUE THREAD

**Issue by adrianromero** [edvin/fxldemo#1]
The POM build example is great but I am also missing a Gradle build example.

**Comment by edvin** [comment]
I've never used Gradle, but I'll give it a shot :) Give me a couple of days.

**Comment by edvin** [comment]
Wow, Gradle was fun :) I've created a seemingly working Gradle example at https://github.com/edvin/fxldemo-gradle, see https://github.com/edvin/fxldemo-gradle/blob/master/build.gradle for more info.

As I've never used Gradle before, I make no promises, but please let me know if I made any mistakes or if there are better ways of doing this.

**Comment by adrianromero** [comment]
Thanks Edvin. This has been really fast. I will have a look at the gradle build.
