### ISSUE TITLE
maven scp

### ISSUE THREAD

**Issue by valerie-taesch** [edvin/fxldemo#4]
Hello,

thanks for the fxlauncher, it is great !

I just have an issue with the scp deploy (with maven).

I updated the properties in my pom.xml,
but `mvn exec:exec@deploy-app` does not work.

I get this exception : 

```
Could not find goal 'exec@deploy-app' in plugin org.codehaus.mojo:exec-maven-plugin:1.4.0 among available goals exec, help, java -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.
```

**Comment by edvin** [comment]
Hi! The command should be correct, provided you have an excution block with id `deploy-app`. Can you post your pom.xml?

**Comment by valerie-taesch** [comment]
The block with id `deploy-app` is in my pom.xml

I have just understand the problem :/
I'm using Maven 3.0.5 but the @ notation in only available since Maven 3.3.1

I will update my Maven installation...

**Comment by edvin** [comment]
Ah, good catch :) Thanks for letting me know.

**Comment by valerie-taesch** [comment]
Thanks for your fast answers :) 
It's ok now !
