### ISSUE TITLE
Two different versions with the same code

### ISSUE THREAD

**Issue by ign4z** [edvin/fxldemo#6]
Hi guys,

I need to create 2 versions of the same application and I need to install them in the same windows machine. 
The problem is that when i try to install the second application is saved in the same directory even if I changed the name of the application.

My installer plugin is following 

`
<execution>
                        <id>installer</id>
                        <phase>install</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>${java.home}/../bin/javapackager</executable>
                            <arguments>
                                <argument>-deploy</argument>
                                <argument>-native</argument>
                                <argument>-outdir</argument>
                                <argument>${app.installerdir}</argument>
                                <argument>-outfile</argument>
                                <argument>${app.filename}</argument>
                                <argument>-srcdir</argument>
                                <argument>${app.dir}</argument>
                                <argument>-srcfiles</argument>
                                <argument>fxlauncher.jar</argument>
                                <argument>-appclass</argument>
                                <argument>fxlauncher.Launcher</argument>
                                <argument>-name</argument>
                                <argument>${project.artifactId}</argument>
                                <argument>-title</argument>
                                <argument>${project.artifactId}</argument>
                                <argument>-vendor</argument>
                                <argument>${app.vendor}</argument>
                                <argument>-BappVersion=${app.version}</argument>
                                <argument>-Bicon=${project.basedir}/package/${application.title}</argument>
                                <argument>-v</argument>
                                <argument>-BjvmOptions=-Xmx1G</argument>
                                <argument>-BjvmOptions=-XX:+UseG1GC
                                <argument>-BjvmOptions=-XX:+UseStringDeduplication
                            </arguments>
                        </configuration>
                    </execution>
`

Loking at the `inno setup file (.ISS)` I found that the directory is correctly configured,  but the AppId paramiter is the same : 

`[Setup]
AppId={{fxlauncher}}
AppName=prova
`
Thank you.

**Comment by edvin** [comment]
Can you try to include `<argument>-Bidentifier=${project.groupId}.${project.artifactId}</argument>` in your build, like the [fxldemo project](https://github.com/edvin/fxldemo) does? Does that solve the issue?

**Comment by ign4z** [comment]
Oh yeah! Thank you! 
I tried to use `<argument>-id</argument><argument>${project.artifactId}</argument>` and it doesn't works. 

It would be nice to have the complete documentation with all parameters 👍

**Comment by edvin** [comment]
The parameters is listed in the [JavaPackager Docs](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javapackager.html), but we will soon introduce a Maven plugin that will make the whole thing much easier to reason about :)
